from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 300)
        Dialog.setMinimumSize(QSize(450, 300))
        Dialog.setMaximumSize(QSize(450, 300))
        Dialog.setWindowIcon(QIcon('calculadora.png'))
        self.label = QLabel(Dialog)
        self.label.setGeometry(QRect(190, 10, 81, 31))
        font = QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QLabel(Dialog)
        self.label_2.setGeometry(QRect(10, 60, 201, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QLabel(Dialog)
        self.label_4.setGeometry(QRect(30, 140, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QLabel(Dialog)
        self.label_5.setGeometry(QRect(10, 140, 16, 16))
        font = QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QLabel(Dialog)
        self.label_6.setGeometry(QRect(30, 170, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QLabel(Dialog)
        self.label_7.setGeometry(QRect(10, 170, 16, 16))
        font = QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QLabel(Dialog)
        self.label_8.setGeometry(QRect(150, 110, 21, 16))
        font = QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QLabel(Dialog)
        self.label_9.setGeometry(QRect(170, 110, 81, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QLabel(Dialog)
        self.label_10.setGeometry(QRect(30, 110, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QLabel(Dialog)
        self.label_11.setGeometry(QRect(7, 110, 16, 16))
        font = QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QLabel(Dialog)
        self.label_12.setGeometry(QRect(150, 140, 16, 16))
        font = QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QLabel(Dialog)
        self.label_13.setGeometry(QRect(170, 140, 61, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QLabel(Dialog)
        self.label_14.setGeometry(QRect(150, 170, 16, 16))
        font = QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QLabel(Dialog)
        self.label_15.setGeometry(QRect(170, 170, 91, 16))
        self.label_15.setObjectName("label_15")
        self.label_18 = QLabel(Dialog)
        self.label_18.setGeometry(QRect(10, 230, 351, 16))
        self.label_20 = QLabel(Dialog)
        self.label_20.setGeometry(QRect(10, 280, 271, 16))
        self.label_20.setObjectName("label_20")

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Ajuda"))
        self.label.setText(_translate("Dialog", "Ajuda"))
        self.label_2.setText(_translate("Dialog", "Como Manuseiar a Calculator P1102 V2.0"))
        self.label_4.setText(_translate("Dialog", "  =  Subtração"))
        self.label_5.setText(_translate("Dialog", "-"))
        self.label_6.setText(_translate("Dialog", "  =  Multiplação"))
        self.label_7.setText(_translate("Dialog", "*"))
        self.label_8.setText(_translate("Dialog", "**"))
        self.label_9.setText(_translate("Dialog", "  =  Potênciação"))
        self.label_10.setText(_translate("Dialog", "  =  Subtração"))
        self.label_11.setText(_translate("Dialog", "+"))
        self.label_12.setText(_translate("Dialog", "/"))
        self.label_13.setText(_translate("Dialog", "  =  Divisão"))
        self.label_14.setText(_translate("Dialog", "//"))
        self.label_15.setText(_translate("Dialog", "  =  Divisão Inteira"))
        self.label_18.setText(_translate("Dialog", "Divisão Inteira  :=  Mostrar o resultado somente do quociente da divisão"))
        self.label_20.setText(_translate("Dialog", "Tema escuro disponível para melhores experiências 😀!"))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    Dialog = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
